name: price-predictor
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.3.2
  - numpy=1.26.4
  - scikit-learn=1.5.0
  - pip
  - pip:
    - lightgbm==4.3.0
    - optuna==3.6.1
    - mlflow==3.3.2
    - streamlit==1.49.1
    - plotly==6.3.0
    - seaborn==0.13.2
    - matplotlib==3.9.0
    - pyyaml==6.0.2
    - requests==2.32.2
    - joblib==1.4.2
    - python-dotenv==1.1.0
